# Generated by Django 4.1.2 on 2022-10-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_artiste_last_name_alter_lyric_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_lyrics', to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_songs', to='musicapp.artiste'),
        ),
    ]
